### ISSUE TITLE
Remove res (argument) from LinkedIn.auth.getAccessToken call

### ISSUE THREAD

**Issue by ArkeologeN** [ArkeologeN/node-linkedin#14]

**Comment by zgianos** [comment]
You can safely ignore the `res` (HTTP response object) argument by passing in the access code as the first argument.

```javascript
linkedin.auth.getAccessToken(req.query.code, req.query.state, function(err, results) { /*...*/ });
```

**Comment by ArkeologeN** [comment]
@zgianos Thanks for the help. Did you added it in README as well?

**Comment by zgianos** [comment]
@ArkeologeN There is a comment in the example code that was already there.
