### ISSUE TITLE
This module is support API to posting Jobs to linkedin?

### ISSUE THREAD

**Issue by aredo** [ArkeologeN/node-linkedin#30]
i just curious this module can do posting jobs to linkedin if user have been connected to linkedin?
if not, you know what the API or how to make it works?

Thanks in advance.

**Comment by ArkeologeN** [comment]
This module cannot do job posting at the moment. Though, posting job is a paid `premium` feature. You may take a look at their API docs and if you find it interesting, feel free to do the implementation and send the pull request.
