### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by throrin19** [ArkeologeN/node-linkedin#31]
Hi, 
I want to use this library on my project but, i want to use this library in automation part. It's not possible, in this part, to access on Oauth2 dialog Box. It's possible to get access Token without this ?

**Comment by ArkeologeN** [comment]
Hey,

As far as I know- Its not possible in OAuth 2.0 to retrieve user's token without asking them for permissions. However, `github` has the feature of `personal access tokens` which you could find on the link below (you've to be logged in):

https://github.com/settings/applications

Once you create the `personal access token`, you can use that straight away with 

```javascript
var linkedin = Linkedin.init("TOKEN_HERE");
```

And it should work!

**Comment by chovy** [comment]
what does github token have to do with linked in api?
