### ISSUE TITLE
Exchanging auth code for token now requires POST 

### ISSUE THREAD

**Issue by sinejoe** [ArkeologeN/node-linkedin#35]
As shown here in step 3, https://developer.linkedin.com/docs/oauth2, the exchanging of access token requires **POST** method with content-type set to **application/x-www-form-urlencoded**. This package uses request.get not request.post. Not sure when this changed but getting access token definitely is no longer working.

**Comment by ArkeologeN** [comment]
I see. Yep, sound's like the LinkedIn has made a change in their core structure so we have to update the module to reflect the change. Would you be able to submit pull-request for the discussed issue or otherwise, I will fix that and push once available.

**Comment by sinejoe** [comment]
Yes, working on it now... give me a few.

**Comment by ArkeologeN** [comment]
I already got your pull-request though didn't tested! ;) Closing the issue now.
