### ISSUE TITLE
authentication error , even after everything is set up perfectly ! 

### ISSUE THREAD

**Issue by weezyboyaxy** [ArkeologeN/node-linkedin#39]
![linked in error](https://cloud.githubusercontent.com/assets/9816692/7633506/0686ec4c-fa72-11e4-91bd-b407a4c43170.PNG)

error url --> https://www.linkedin.com/uas/oauth2/authorization?response_type=code&client_id=api&scope=r_basicprofile%20r_emailaddress%20w_share&state=0.3896433834452182&redirect_uri=callback 

can you say me what could be the error ?!

Please help me out ASAP , i would be very thankful to you :+1:

**Comment by ArkeologeN** [comment]
It could be due to the following reason:

- Your `stateIn` and `stateOut` doesn't match.
- The token is invalid and/or expired.
- `callback` url needs to be there instead of `&redirect_uri=callback`.

**Comment by weezyboyaxy** [comment]
im sorry but @ArkeologeN  ur hints , didn't help me !

Everything is perfect in my code & still authentication error exists ! 

Im thinking that , this error may exist coz of the linkedin API restriction & Partnership program :)

**Comment by weezyboyaxy** [comment]
waiting for u confirmation @ArkeologeN ! is it because of restriction of api usage to every1 & partnership integration ?!

**Comment by niknah** [comment]
As of 12-19/May, the sample code for this module no longer works.  You need to remove some permissions...
https://developer.linkedin.com/support/developer-program-transition

> To correct this issue, ensure that the scope parameter in your authorization workflow is no longer requesting any of the following member permissions:
>
> r_fullprofile, r_network, r_contactinfo, rw_nus, rw_groups, w_messages.


The sample code was confusing for me.  "api" actually refers to "client id".


```
var Linkedin = require('node-linkedin')('Client id', 'client secret', 'http://yourserver.com/oauth/linkedin/callback');

// Using a library like `expressjs` the module will 
// redirect for you simply by passing `res`. 
app.get('/oauth/linkedin', function(req, res) {
    // This will ask for permisssions etc and redirect to callback url. 
    Linkedin.auth.authorize(res, ['r_basicprofile']);
});
 
// otherwise you can leave `res` out, and the module will respond with the redirect url 
Linkedin.auth.authorize(['r_basicprofile']);
 
// Again, `res` is optional, you could pass `code` as the first parameter 
// Be sure to pass the `state` parameter to verify no CSRF intrusion, see [step 2 here](https://developer.linkedin.com/docs/oauth2) 
app.get('/oauth/linkedin/callback', function(req, res) {
    Linkedin.auth.getAccessToken(res, req.query.code, req.query.state, function(err, results) {
        if ( err )
            return console.error(err);
 
        /**
         * Results have something like:
         * {"expires_in":5184000,"access_token":". . . ."}
         */
        console.log(results);
        var linkedin = Linkedin.init(results.access_token);
        linkedin.people.me(function(err, $in) {
                console.log($in);
        });

        return res.redirect('/');
    });
});
```

**Comment by weezyboyaxy** [comment]
still the error exists bro !

Are u able to establish authorization ?! @niknah !

**Comment by niknah** [comment]
Yes.  The sample code is confusing.  Use my sample instead.

Judging by the link you provided, you need to change 'api' to your 'client id', and remove r_emailaddress,w_share from the permissions.  And change "callback" to the callback url on your webserver.

**Comment by ArkeologeN** [comment]
@weezyboyaxy this most likely to happen when your pre-registered scopes doesn't match with the one you're passing with `node-linkedin` client.

The error you're facing doesn't belongs to the wrapper itself but with interaction with Linkedin API. Please check:

- You have valid API Key (Client ID)
- You have valid API Secret 
- You have valid callback address.
- Your callback is fully accessible with the state.
- Your scopes `[ r_emailaddress .... ]` and others matches with the specification defined while created application on LinkedIn Developer.
- You have access to private APIs (Job API) etc before invoking them.
- You're not reaching the rate limit.

Let me know if its fruitful for you! :)

**Comment by niknah** [comment]
In the above comment, he mentions that this was his url...

https://www.linkedin.com/uas/oauth2/authorization?response_type=code&client_id=api&scope=r_basicprofile%20r_emailaddress%20w_share&state=0.3896433834452182&redirect_uri=callback

You can see that the client_id has just been left is "api" and "callback" is just callback.

The sample code doesn't explain where you should put things.
How does someone know that you're supposed to put the "client id" in the string where it says "api"?
The "callback" in the example is confusing, what you mean is the callback url that you put in the application.  There's no mention in the example that you're supposed to change this to anything other than "callback".
.init(access_token) is mentioned before we even have an access_token.

I had the same problems too.

**Comment by weezyboyaxy** [comment]
@ArkeologeN  & @niknah   both of u thank you for giving me the brief about error , im dropping my code , please let me know , if i am wrong from my side 

[code]
var api = '**********';
var secret = '***********';
var callback = 'http://localhost:1337/oauth/linkedin/callback';

var express = require('express');
var Linkedin = require('node-linkedin')('api', 'secret', 'callback');
var app = express();
var bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({
    extended : true
}));
//  content-type: text/plain; charset=UTF-8 - for Amazon SES-SNS
app.use(bodyParser.text({
    limit : 1231321
}));
//  content-type: application/json - for VideoCRM
app.use(bodyParser.json({
    limit : 24651546
}));


app.get('/oauth/linkedin', function(req, res) {
    // This will ask for permisssions etc and redirect to callback url. 
    Linkedin.auth.authorize(res, ['r_basicprofile']);
});

// otherwise you can leave `res` out, and the module will respond with the redirect url 
Linkedin.auth.authorize(['r_basicprofile']);

// Again, `res` is optional, you could pass `code` as the first parameter 
// Be sure to pass the `state` parameter to verify no CSRF intrusion, see [step 2 here](https://developer.linkedin.com/docs/oauth2) 
app.get('/oauth/linkedin/callback', function(req, res) {
    Linkedin.auth.getAccessToken(res, req.query.code, req.query.state, function(err, results) {
        if ( err )
            return console.error(err);

        /**
         * Results have something like:
         * {"expires_in":5184000,"access_token":". . . ."}
         */
        console.log(results);
        var linkedin = Linkedin.init(results.access_token);
        linkedin.people.me(function(err, $in) {
                console.log($in);
        });

        return res.redirect('/');
    });
});

app.listen(1337);
console.log('-------------> Listening at 1337');

[/code] 

please let me know if i made any mistake !

**Comment by niknah** [comment]
Change the  line to...  (remove quotes)

var Linkedin = require('node-linkedin')(api, secret, callback);


And "callback" needs to be something other than localhost.  Do you have a public ip address for your machine?  One that can be accessed by linkedin?

**Comment by weezyboyaxy** [comment]
yea , i vl try bro & yea we do have public ip , 

Let me try & get back to u :+1:  thanx 4 the swift reply :)

**Comment by weezyboyaxy** [comment]
wow , Thank you  bro , the whole was in dz line -> var Linkedin = require('node-linkedin')(api, secret, callback); 

i was getting error cause , i was using quotes ! thanx alot bro O:) u saved my time , im v.thankful to u @niknah

**Comment by weezyboyaxy** [comment]
![linkedin console](https://cloud.githubusercontent.com/assets/9816692/7722582/34ad0bec-feff-11e4-947d-26dc9452dfb9.PNG)

![csrf alert](https://cloud.githubusercontent.com/assets/9816692/7722602/6185d5ae-feff-11e4-8348-4f582146a98b.PNG)

and check the bellow code !
var api = ********* ;
var secret = ****** ;
var callback = 'http://localhost:1337/oauth/linkedin/callback';

var express = require('express');
var Linkedin = require('node-linkedin')(api, secret, callback);
var app = express();
var bodyParser = require('body-parser');

var linkedin = Linkedin.init('my_access_token', {
    timeout: 10000 /* 10 seconds */
});

app.use(bodyParser.urlencoded({
    extended : true
}));
//  content-type: text/plain; charset=UTF-8 - for Amazon SES-SNS
app.use(bodyParser.text({
    limit : 1231321
}));
//  content-type: application/json - for VideoCRM
app.use(bodyParser.json({
    limit : 24651546
}));


app.get('/oauth/linkedin', function(req, res) {
    // This will ask for permisssions etc and redirect to callback url. 
    Linkedin.auth.authorize(res, ['r_basicprofile', 'r_fullprofile', 'r_emailaddress', 'r_network', 'r_contactinfo', 'rw_nus', 'rw_groups', 'w_messages']);
});

// otherwise you can leave `res` out, and the module will respond with the redirect url 
Linkedin.auth.authorize(['r_basicprofile', 'r_fullprofile', 'r_emailaddress', 'r_network', 'r_contactinfo', 'rw_nus', 'rw_groups', 'w_messages']);

// Again, `res` is optional, you could pass `code` as the first parameter 
// Be sure to pass the `state` parameter to verify no CSRF intrusion, see [step 2 here](https://developer.linkedin.com/docs/oauth2) 
app.get('/oauth/linkedin/callback', function(req, res) {
    Linkedin.auth.getAccessToken(res, req.query.code, req.query.state, function(err, results) {
        if ( err )
            return console.error(err);

        /**
         * Results have something like:
         * {"expires_in":5184000,"access_token":". . . ."}
         */
        console.log(results);
				var linkedin = Linkedin.init(results['access_token']);
					// https://developer.linkedin.com/forum/what-difference-between-count-and-total-linkedin-j-apis
					return linkedin.connections.retrieve(function(err, connections) {
					var contacts = [];
					for(var idx in connections.values) {
						var contact = connections.values[idx];
						contacts.push({
							FirstName: contact.firstName,
							LastName: contact.lastName,
							LinkedInID: contact.id
						});
					}
					console.log(contacts);
					res.setHeader('linkedinaccesstoken', results['access_token']);
					return res.end(JSON.stringify(contacts));
				
			
				});
    });
});

app.listen(1337);
console.log('-------------> Listening at 1337');


eventhough im havng correct code & full access ! im getting CSRF alert now :(  before , with basic profile i was able to get my details , after wards i tried with above code and csrf error arised !

**Comment by ArkeologeN** [comment]
The error is raised from here:

https://github.com/ArkeologeN/node-linkedin/blob/master/lib/auth.js#L51

**Comment by niknah** [comment]
You're asking for all the permissions.  Which hasn't been available since 12/May.
Only ask for ['r_basicprofile']
I've removed this in my sample above.

Print out req.query from the callback.  There should be an error message.

**Comment by ArkeologeN** [comment]
Closing the issue due to no hear.
