### ISSUE TITLE
Problems with new CSRF check related to stateIn

### ISSUE THREAD

**Issue by reillydavis** [ArkeologeN/node-linkedin#40]
We've experienced a few problems with stateIn. 

First, if you're running on Heroku (or any distributed system), since the stateIn is stored on the global object, it won't work if the initial request and next request hit different machines. 

Second, I believe that if you're getting many authentication requests at the same time, there is a race condition when reaching getAccessToken because the state could have changed since the authorized request was sent. 

I'm not sure how it could be fixed without removing the new CSRF check?

**Comment by ArkeologeN** [comment]
If that could do the job that we could remove the state check but I believe, that state check is from LinkedIn right? And if not- you could make it optional and send me pull request :)

**Comment by erickuribe91** [comment]
Hello 

I solved the problem by assigning a string to  state as indicated  <a href="https://developer.linkedin.com/docs/oauth2#ux ">CSFR</a> 

var state = "i8XNjC4b8KVok4uw5RftR38Wgp2BFwql";


var Linkedin = require('node-linkedin')(api, secret, callback, state);

app.get('/oauth/linkedin/callback', function(req, res) {

console.log(state);
Linkedin.auth.getAccessToken(res, req.query.code, state, function(err, results) {
  

  if ( err )
  return console.error(err);
  console.log(results);

  });
});

**Comment by ArkeologeN** [comment]
@erickuribe91 Could you please send me the pull request?
