### ISSUE TITLE
LinkedIn Permissions

### ISSUE THREAD

**Issue by snapptop** [ArkeologeN/node-linkedin#52]
Hi - I just had a few questions on permissions. When I create an App on LinkedIn, by default, my App can only be granted the following perms:

```
"scope": ["r_basicprofile",	"r_emailaddress","rw_company_admin","w_share"]
```

Reading the current documentation on LinkedIn, it looks like I have to apply to be some sort of "Partner" with them to get extended permissions? Is that correct? Have they just recently removed some of the default permissions? Is it easy to get approval for extended permissions? If I am a "Premium" member can I access more scopes?

Sorry to bombard you with questions - I am noticing a lot of APIs are getting very restrictive lately - almost to the point where there is no use in having an api at all :) Thanks for the help

**Comment by ArkeologeN** [comment]
That's right. You need to apply for the Partner program to receive access to extended service. Lately, people had used those heaven-like APIs to build their own entire products which made the companies realize that the only money left anymore is `Data` and we're doing it charity with a free access to public APIs :)

**Comment by snapptop** [comment]
Well shit .. there goes my plan :( Thanks for reply
