### ISSUE TITLE
Linkedin Share via node.js

### ISSUE THREAD

**Issue by bhummesh** [ArkeologeN/node-linkedin#57]
I need to share my message from my linkedin app through node.js

**Comment by ArkeologeN** [comment]
Please follow these links:

To share as company:
https://github.com/ArkeologeN/node-linkedin/blob/001f6e5229ef17782c7a2310e880e5e0ded272d4/specs/services/companies_spec.js#L101

To share as an individual:
https://github.com/ArkeologeN/node-linkedin/blob/8802eacd73c81accf25d5c7cb7abb01e1d00b3ad/specs/services/people_spec.js#L45

Pardon for not having the README available.

**Comment by bhummesh** [comment]
I need solution to logout from linkedin,twitter passport oauth through node.js
