### ISSUE TITLE
I am getting error "Internal service error" while using  api of get statistics for a company page.

### ISSUE THREAD

**Issue by dhirajsharma072** [ArkeologeN/node-linkedin#65]
I am using  linkedin.companies.company_stats(page.id,callback) and getting response from API  is given below:
{ 
errorCode: 0,
  message: 'Internal service error',
  requestId: 'TSY816T5K6',
  status: 500,
  timestamp: 1459974559087
 } 
Currently I am using node-linkedin version 0.5.3.
Please suggest me solution for this.
Thanks !

**Comment by ArkeologeN** [comment]
It could be due to the issue in LinkedIn itself. I don't remember as if there's such a way of error exists in module.

**Comment by dhirajsharma072** [comment]
Thanks!! LinkedIn api was down due to that I was getting error.

**Comment by dreadjr** [comment]
@dhirajsharma072 How did you verify that the linkedin api was down? I can't find any support webpage, email, etc. What is most frustrating is that I am getting the same error on the `share` method but it actually is posting.
