### ISSUE TITLE
Need to be ask always Linkedin Login for reauthontication

### ISSUE THREAD

**Issue by SantoshSKhavekar** [ArkeologeN/node-linkedin#78]
Hi Team,

 I have to display linkedin login page everytime to reauthontication.I have been tried the below flow to work out this but unfortunatly not able to do it.

var Linkedin = require('node-linkedin')(config.linkedin_clientId,config.linkedin_secret,config.linkedin_redirectUrl);
var scope = ['r_basicprofile','r_emailaddress','rw_company_admin','w_share'];
var auth_url = Linkedin.auth.authorize(scope);
How to do ? can someone help me in this?

Thanks in advance.

**Comment by ArkeologeN** [comment]
@SantoshSKhavekar 

The LinkedIn login only appears once until the user is not logged in or haven't granted permissions to your app. Once he did that, LinkedIn set the cookies to prevent re-login screen every time.
