### ISSUE TITLE
Question: support for iOS5+?

### ISSUE THREAD

**Issue by RyanQuey** [ArkeologeN/node-linkedin#80]
I noticed that the JavaScript SDK for LinkedIn doesn't support iOS 5+.

Does node-LinkedIn? Thanks!

**Comment by ArkeologeN** [comment]
Hi, I'm not sure as I didn't end up to such situation.We're a JS wrapper if you can run JS on your iOS device (which you can!), then the wrapper works too!

**Comment by RyanQuey** [comment]
I'm just checking because LinkedIn specifically said that they don't support iOS 5+ in their documentation

See [here](https://stackoverflow.com/questions/29230820/sign-in-with-linkedin-doesnt-trigger-callback-on-ios-safari-when-using-the-js-a)

![image](https://user-images.githubusercontent.com/22231483/30219690-af5de5dc-9471-11e7-9e7a-1b27b346c2b7.png)

**Comment by ArkeologeN** [comment]
We're backend module, for usage in APIs, therefore, I cannot comment. However, it seems they wrote about their JavaScript SDK and we're API wrapper :)
