### ISSUE TITLE
No error on wrong access token during init.

### ISSUE THREAD

**Issue by umarhussain15** [ArkeologeN/node-linkedin#81]
If I give a wrong accesstoken to the init function, does it throws any error ? because after that when I try to retrieve the profile the error is null and the userResult json contains error code 0 and status code 401

**Comment by ArkeologeN** [comment]
I'm afraid because when you pass it to `init`, it just set it internally in the wrapper for later use. Once you actually call an endpoint, the token is sent and a response is given as described.
